# Towards a better context space for explanation

In [1]:
%load_ext autoreload
%autoreload 2

from IPython.display import display, HTML
import sys
import os
from os import path

sys.path.append("./../src")
tmp_path = path.join('.cache', '2023-01-10')
os.makedirs(tmp_path,exist_ok=True)

## 1. Check LSTM vs LSTM+Attention

In [2]:
import pandas as pd

summary = dict()
for dataset in ['esnli', 'yelphat50', 'hatexplain']:
    summary[dataset] = pd.read_parquet(f'/Users/dunguyen/Projects/IGRIDA/historic/2022-12-13/summary/overfitting_check/lstm_vanilla/{dataset}/summary.parquet')

In [3]:
df_summary = pd.concat(list(summary.values()))
df_summary = df_summary.groupby(['data', 'n_context'])[['y:fscore']].agg(['mean', 'sem'])

df_summary['y:fscore','ci95_hi'] = df_summary['y:fscore', 'mean'] + 1.96* df_summary['y:fscore','sem']
df_summary['y:fscore','ci95_lo'] = df_summary['y:fscore', 'mean'] + 1.96* df_summary['y:fscore','sem']
df_summary['y:fscore','value'] = df_summary['y:fscore', 'mean'].round(3).map(str) + '±' + (1.96* df_summary['y:fscore','sem']).round(3).map(str)
df_summary

                      y:fscore
                          mean       sem   ci95_hi   ci95_lo        value
data       n_context
esnli      1          0.802477  0.000776  0.803997  0.803997  0.802±0.002
           2          0.799959  0.001828  0.803542  0.803542    0.8±0.004
           3          0.793045  0.001622  0.796225  0.796225  0.793±0.003
           4          0.787474  0.001082  0.789595  0.789595  0.787±0.002
           5          0.777031  0.002363  0.781662  0.781662  0.777±0.005
           6          0.773835  0.000806  0.775415  0.775415  0.774±0.002
hatexplain 1          0.627207  0.007367  0.641646  0.641646  0.627±0.014
           2          0.624128  0.010937  0.645563  0.645563  0.624±0.021
           3          0.633091  0.008695  0.650133  0.650133  0.633±0.017
           4          0.626039  0.006064  0.637925  0.637925  0.626±0.012
           5          0.620630  0.005861  0.632118  0.632118  0.621±0.011
           6          0.636552  0.001799  0.640078  0.640078  0.637±0.004
yelphat50  1          0.790000  0.010184  0.809960  0.809960    0.79±0.02
           2          0.826667  0.017638  0.861238  0.861238  0.827±0.035
           3          0.908889  0.009095  0.926715  0.926715  0.909±0.018
           4          0.842222  0.051002  0.942187  0.942187    0.842±0.1
           5          0.915556  0.004006  0.923408  0.923408  0.916±0.008
           6          0.865556  0.030449  0.925236  0.925236   0.866±0.06

## 2. Check input dimension in LSTM+Attention

In [15]:
df_summary = pd.concat(list(summary.values()))

In [16]:
df_summary.index

Index(['run=1_esnli_dim=100_nlstm=3_concat=1',
       'run=1_esnli_dim=100_nlstm=1_concat=1',
       'run=0_esnli_dim=100_lstm=3_concat=1',
       'run=0_esnli_dim=50_lstm=1_concat=1',
       'run=0_esnli_dim=100_lstm=1_concat=1',
       'run=2_esnli_dim=100_nlstm=3_concat=1',
       'run=1_esnli_dim=50_lstm=3_concat=1',
       'run=0_esnli_dim=100_lstm=5_concat=1',
       'run=0_esnli_dim=50_lstm=3_concat=1',
       'run=0_yelphat50_dim=300_nlstm=3_concat=1',
       'run=2_yelphat50_dim=300_nlstm=3_concat=1',
       'run=0_yelphat50_dim=300_nlstm=1_concat=1',
       'run=1_yelphat50_dim=300_nlstm=1_concat=1',
       'run=1_yelphat50_dim=300_nlstm=5_concat=1',
       'run=1_yelphat50_dim=300_nlstm=3_concat=1',
       'run=2_yelphat50_dim=300_nlstm=5_concat=1',
       'run=0_yelphat50_dim=300_nlstm=5_concat=1',
       'run=2_yelphat50_dim=300_nlstm=1_concat=1',
       'run=2_hatexplain_dim=300_nlstm=3_concat=1',
       'run=0_hatexplain_dim=300_nlstm=1_concat=1',
       'run=1_hatexplain_dim=300_nlstm=1_concat=1',
       'run=1_hatexplain_dim=300_nlstm=3_concat=1',
       'run=2_hatexplain_dim=300_nlstm=5_concat=1',
       'run=1_hatexplain_dim=300_nlstm=5_concat=1',
       'run=2_hatexplain_dim=300_nlstm=1_concat=1',
       'run=0_hatexplain_dim=300_nlstm=5_concat=1',
       'run=0_hatexplain_dim=300_nlstm=3_concat=1'],
      dtype='object')

In [7]:

summary = dict()
for dataset in ['esnli', 'yelphat50', 'hatexplain']:
    summary[dataset] = pd.read_parquet(f'/Users/dunguyen/Projects/IGRIDA/historic/2022-12-13/summary/overfitting_check/embedding_dimension_variation/{dataset}/summary.parquet')
    
df_summary = pd.concat(list(summary.values()))

metric = 'y:fscore'
df_summary = df_summary.groupby(['data', 'n_context'])[[metric]].agg(['mean', 'sem'])

df_summary[metric,'ci95_hi'] = df_summary[metric, 'mean'] + 1.96* df_summary[metric,'sem']
df_summary[metric,'ci95_lo'] = df_summary[metric, 'mean'] + 1.96* df_summary[metric,'sem']
df_summary[metric,'value'] = df_summary[metric, 'mean'].round(3).map(str) + '±' + (1.96* df_summary[metric,'sem']).round(3).map(str)
display(HTML(f'<h3>{metric}</h3>'))
df_summary

                      y:fscore
                          mean       sem   ci95_hi   ci95_lo        value
data       n_context
esnli      1          0.795060  0.005117  0.805090  0.805090   0.795±0.01
           3          0.786686  0.003471  0.793489  0.793489  0.787±0.007
           5          0.777178       NaN       NaN       NaN    0.777±nan
hatexplain 1          0.665974  0.004505  0.674802  0.674802  0.666±0.009
           3          0.642412  0.002382  0.647080  0.647080  0.642±0.005
           5          0.645357  0.001758  0.648803  0.648803  0.645±0.003
yelphat50  1          0.926667  0.013333  0.952800  0.952800  0.927±0.026
           3          0.621111  0.059701  0.738125  0.738125  0.621±0.117
           5          0.926667  0.001924  0.930439  0.930439  0.927±0.004

In [9]:
df_summary.keys()

MultiIndex([('y:fscore',    'mean'),
            ('y:fscore',     'sem'),
            ('y:fscore', 'ci95_hi'),
            ('y:fscore', 'ci95_lo'),
            ('y:fscore',   'value')],
           )

In [10]:
metric = 'a:AUPRC'
df_summary = pd.concat(list(summary.values()))
df_summary = df_summary.groupby(['data', 'n_context'])[[metric]].agg(['mean', 'sem'])

df_summary[metric,'ci95_hi'] = df_summary[metric, 'mean'] + 1.96* df_summary[metric,'sem']
df_summary[metric,'ci95_lo'] = df_summary[metric, 'mean'] + 1.96* df_summary[metric,'sem']
df_summary[metric,'value'] = df_summary[metric, 'mean'].round(3).map(str) + '±' + (1.96* df_summary[metric,'sem']).round(3).map(str)
display(HTML(f'<h3>{metric}</h3>'))
df_summary

                       a:AUPRC
                          mean       sem   ci95_hi   ci95_lo        value
data       n_context
esnli      1          0.465807  0.000556  0.466897  0.466897  0.466±0.001
           3          0.386078  0.002231  0.390451  0.390451  0.386±0.004
           5          0.296540       NaN       NaN       NaN    0.297±nan
hatexplain 1          0.551350  0.024242  0.598864  0.598864  0.551±0.048
           3          0.390399  0.012761  0.415410  0.415410   0.39±0.025
           5          0.366756  0.004852  0.376266  0.376266   0.367±0.01
yelphat50  1          0.406263  0.030137  0.465332  0.465332  0.406±0.059
           3          0.262250  0.048398  0.357111  0.357111  0.262±0.095
           5          0.178003  0.020692  0.218559  0.218559  0.178±0.041